---
version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper${CONFLUENT_VERSION_TAG}
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka${CONFLUENT_VERSION_TAG}
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,IP_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092,IP_LISTENER://192.168.1.78:39092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry${CONFLUENT_VERSION_TAG}
    ports:
      - 8081:8081
    container_name: schema-registry
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:9092
      SCHEMA_REGISTRY_CUB_KAFKA_TIMEOUT: 300
    restart: unless-stopped

  kafka-connect:
    image: entechlog/cp-kafka-connect${CONFLUENT_VERSION_TAG}
    container_name: kafka-connect
    build:
      context: ./docker/
      args:
        CONNECTOR_OWNER: ${CONNECTOR_OWNER}
        CONNECTOR_NAME: ${CONNECTOR_NAME}
        CONNECTOR_VERSION: ${CONNECTOR_VERSION}
    ports:
      - 8083:8083
    environment:
      CUB_CLASSPATH: '/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-security/connect/*:/usr/share/java/kafka/*'
      CONNECT_CUB_KAFKA_TIMEOUT: 300
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      CONNECT_REST_ADVERTISED_HOST_NAME: 'kafka-connect'
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _kafka-connect-group-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _kafka-connect-group-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _kafka-connect-group-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_LOG4J_ROOT_LOGLEVEL: 'INFO'
      CONNECT_LOG4J_LOGGERS: 'org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR'
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: '2'
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: '2'
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: '2'
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/,/data/connect-jars'
      # External secrets config
      # See https://docs.confluent.io/current/connect/security.html#externalizing-secrets
      CONNECT_CONFIG_PROVIDERS: 'file'
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: 'org.apache.kafka.common.config.provider.FileConfigProvider'

      # Class path to add custom authentication
      CLASSPATH: '/etc/kafka/secrets/${CLIENT_JAR}:/etc/kafka/secrets/${COMMON_JAR}'
      # Connect Worker
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      # RBAC
      CONNECT_SASL_MECHANISM: 'OAUTHBEARER'
      CONNECT_SASL_LOGIN_CALLBACK_HANDLER_CLASS: ${SASL_LOGIN_CALLBACK_HANDLER_CLASS}
      CONNECT_SASL_JAAS_CONFIG: |
              org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
              username="${KAFKA_USER}" \
              password="${KAFKA_PASSWORD}";

      # Connect Producer
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      # Producer
      CONNECT_PRODUCER_SASL_MECHANISM: 'OAUTHBEARER'
      CONNECT_PRODUCER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: ${SASL_LOGIN_CALLBACK_HANDLER_CLASS}
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: 'OAUTHBEARER'
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_LOGIN_CALLBACK_HANDLER_CLASS: ${SASL_LOGIN_CALLBACK_HANDLER_CLASS}
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: |
              org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
              username="${KAFKA_USER}" \
              password="${KAFKA_PASSWORD}";

      # Connect Consumer
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      # Consumer
      CONNECT_CONSUMER_SASL_MECHANISM: 'OAUTHBEARER'
      CONNECT_CONSUMER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: ${SASL_LOGIN_CALLBACK_HANDLER_CLASS}
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: 'OAUTHBEARER'
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_LOGIN_CALLBACK_HANDLER_CLASS: ${SASL_LOGIN_CALLBACK_HANDLER_CLASS}
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: |
              org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
              username="${KAFKA_USER}" \
              password="${KAFKA_PASSWORD}";

      # Reduce Connect memory utilization
      KAFKA_JVM_PERFORMANCE_OPTS: -server -XX:+UseG1GC -XX:GCTimeRatio=1
                  -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
                  -XX:MaxGCPauseMillis=10000 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent
                  -XX:MaxInlineLevel=15 -Djava.awt.headless=true

      # Set auth config
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/connect.jaas

      # CONNECTOR_ properties are for the connector itself, example shown below
      CONNECT_OFFSET_STORAGE_FILE_FILENAME: /tmp/connect.offsets
      CONNECTOR_NAME: bq-sink-connector
      CONNECTOR_CONNECTOR_CLASS: com.wepay.kafka.connect.bigquery.BigQuerySinkConnector
      CONNECTOR_PROJECT: ${CONNECTOR_PROJECT}
      CONNECTOR_CAMELCASE_DEFAULT_DATASET: ${CONNECTOR_DEFAULT_DATASET}
      CONNECTOR_CAMELCASE_SCHEMA_RETRIEVER: com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever
      CONNECTOR_TOPICS: ${CONNECTOR_TOPICS}
      CONNECTOR_KEY_IGNORE: "true"
      CONNECTOR_SCHEMA_IGNORE: "true"
      CONNECTOR_AUTO_REGISTER_SCHEMAS: "true"
      CONNECTOR_KEYFILE: /etc/kafka/secrets/bq-sink-connector.key
      CONNECTOR_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECTOR_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"
      CONNECTOR_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECTOR_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECTOR_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      CONNECTOR_SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}

    volumes:
      - ./secrets/:/etc/kafka/secrets/
    user: "1000:1000"