-- Select few random records
SELECT *
FROM "DEMO_DB"."PUBLIC"."TWITTER_MY_FAVORITE_CELEBRITIES_SRC_1206524140"
LIMIT 10;

-- Validate the record count
SELECT CURRENT_TIMESTAMP()
	,COUNT(*)
FROM "DEMO_DB"."PUBLIC"."TWITTER_MY_FAVORITE_CELEBRITIES_SRC_1206524140";

-- Parse JSON
-- Field in root    : RECORD_CONTENT:CreatedAt
-- Field in Dict    : RECORD_CONTENT:User.Name
-- Field in Array   : RECORD_CONTENT:HashtagEntities (VALUE:Text::STRING)
SELECT
RECORD_CONTENT:CreatedAt AS "CreatedAt",
RECORD_CONTENT:User.Name AS "UserName",
VALUE:Text::STRING AS "HashTag"
FROM "DEMO_DB"."PUBLIC"."TWITTER_MY_FAVORITE_CELEBRITIES_SRC_1206524140",
LATERAL FLATTEN(INPUT => RECORD_CONTENT:HashtagEntities)
WHERE
RECORD_CONTENT: HashtagEntities <> '[]'
ORDER BY RECORD_CONTENT:CreatedAt DESC;