SET 'auto.offset.reset' = 'earliest';

-- Create RAW Stream
CREATE
	OR REPLACE STREAM STM_WEATHER_ALERT_APP_0010_RAW (ROWKEY VARCHAR KEY)
	WITH (
			KAFKA_TOPIC = 'weather.alert.app.source'
			,VALUE_FORMAT = 'AVRO'
			);

-- Select only required attributes
CREATE OR REPLACE STREAM STM_WEATHER_ALERT_APP_0020_SEL_ATTRIBUTES
	WITH (
			KAFKA_TOPIC = 'STM_WEATHER_ALERT_APP_0020_SEL_ATTRIBUTES',
			VALUE_FORMAT = 'json'
			) AS
SELECT ROWKEY,
	CURRENT -> DT AS CURRENT_DT_TIME,
	CURRENT -> TEMP AS CURRENT_TEMP,
	CURRENT -> WEATHER [1] -> DESCRIPTION AS CURRENT_WEATHER_DESC
FROM STM_WEATHER_ALERT_APP_0010_RAW EMIT CHANGES;

-- Filter out RAIN records only
CREATE
	OR REPLACE STREAM STM_WEATHER_ALERT_APP_0030_RAIN_IS_HERE
	WITH (
			KAFKA_TOPIC = 'STM_WEATHER_ALERT_APP_0030_RAIN_IS_HERE'
			,VALUE_FORMAT = 'json'
			) AS

SELECT *
FROM STM_WEATHER_ALERT_APP_0020_SEL_ATTRIBUTES
WHERE CURRENT_WEATHER_DESC IS NOT NULL
	AND UCASE(CURRENT_WEATHER_DESC) LIKE '%RAIN%'
	EMIT CHANGES;

-- Create stream for unique notification for the day, 
-- This is required because tables don't support INSERT INTO
CREATE
	OR REPLACE STREAM STM_WEATHER_ALERT_APP_0040_UNIQUE_KEY (
	ROWKEY VARCHAR KEY
	,CURRENT_WEATHER_DESC VARCHAR
	)
	WITH (
			KAFKA_TOPIC = 'STM_WEATHER_ALERT_APP_0040_UNIQUE_KEY'
			,VALUE_FORMAT = 'JSON'
			);

-- Create stream for unique notification for the day
CREATE
	OR REPLACE TABLE TBL_WEATHER_ALERT_APP_0050_UNIQUE_KEY AS

SELECT ROWKEY
	,LATEST_BY_OFFSET(CURRENT_WEATHER_DESC) AS CURRENT_WEATHER_DESC
FROM STM_WEATHER_ALERT_APP_0040_UNIQUE_KEY
GROUP BY ROWKEY EMIT CHANGES;

-- Create final stream
CREATE
	OR REPLACE STREAM STM_WEATHER_ALERT_APP_9000_NOTIFY
	WITH (
			KAFKA_TOPIC = 'STM_WEATHER_ALERT_APP_9000_NOTIFY'
			,VALUE_FORMAT = 'JSON'
			) AS

SELECT A.ROWKEY AS ROWKEY
	,A.CURRENT_DT_TIME AS CURRENT_DT_TIME
	,A.CURRENT_TEMP AS CURRENT_TEMP
	,A.CURRENT_WEATHER_DESC AS CURRENT_WEATHER_DESC
FROM STM_WEATHER_ALERT_APP_0030_RAIN_IS_HERE A
LEFT JOIN TBL_WEATHER_ALERT_APP_0050_UNIQUE_KEY B ON A.ROWKEY = B.ROWKEY
WHERE B.ROWKEY IS NULL EMIT CHANGES;

-- Insert into the Unique key stream to avoid duplicate notification
INSERT INTO STM_WEATHER_ALERT_APP_0040_UNIQUE_KEY
SELECT ROWKEY
	,CURRENT_WEATHER_DESC
FROM STM_WEATHER_ALERT_APP_9000_NOTIFY EMIT CHANGES;
